name: Generate Snake

# Déclenche l'action tous les jours à minuit UTC
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Elie-Mos

      - name: Publier le Snake sur GitHub
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: github-contribution-grid-snake.svg
